apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - maistra.io/istio-operator
  name: {{ .Values.serviceMeshInstanceName }}
  namespace: {{ .Values.serviceMeshNamespace }}
spec:
{{- toYaml .Values.serviceMeshInstanceSpec | nindent 2 }}
