apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: default
  namespace: {{ .Values.serviceMeshNamespace }}
spec:
{{- toYaml .Values.serviceMeshMemberRollSpec | nindent 2 }}
