apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    helm.sh/resource-policy: "keep"
  name: {{ .Values.elasticsearchOperatorNamespace }}
spec:
  finalizers:
  - kubernetes
