apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    operators.coreos.com/jaeger-product.openshift-distributed-tracing: ""
  name: jaeger-product
  namespace: {{ .Values.jaegerOperatorNamespace }}
spec:
  channel: {{ .Values.jaegerOperatorChannel }}
  installPlanApproval: {{ .Values.jaegerOperatorInstallPlanApproval }}
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jaeger-operator.{{ .Values.jaegerOperatorVersion }}
